app:
  image: blueimp/nginx:1.8
  volumes:
    - ./app:/usr/share/nginx/html
hub:
  image: selenium/hub:2.48.2
chrome:
  image: selenium/node-chrome:2.48.2
  links:
    - hub
    - app
firefox:
  image: selenium/node-firefox:2.48.2
  links:
    - hub
    - app
chromedebug:
  image: selenium/node-chrome-debug:2.48.2
  links:
    - hub
    - app
  ports:
    - 5900:5900
firefoxdebug:
  image: selenium/node-firefox-debug:2.48.2
  links:
    - hub
    - app
  ports:
    - 5901:5900
protractor:
  image: blueimp/protractor:3.0
  links:
    - hub
  volumes:
    - ./test:/home/node
